### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by fmzarrinkelk** [FMZOrganization/learngitandgithub-salonimodi#1]
Nice code. Just some inconsistent spaces!  :)

I don't mark down for this, but just keep your code nice and clean in the future.

<img width="188" alt="image" src="https://user-images.githubusercontent.com/638756/219935928-6ce418fd-f8b8-422a-9588-7b23a4ca472c.png">

**Comment by fmzarrinkelk** [comment]
Did you test your app in portrait mode?

<img width="439" alt="image" src="https://user-images.githubusercontent.com/638756/219936134-53e47431-7d04-4ab7-bcd6-395cd1517b10.png">

**Comment by fmzarrinkelk** [comment]
Did you ever test your app in portrait mode?

<img width="439" alt="image" src="https://user-images.githubusercontent.com/638756/219936483-30fbf949-3654-4e27-93f5-84a98d44da77.png">

**Comment by fmzarrinkelk** [comment]
0.01 here is probably not your fault here.

<img width="120" alt="image" src="https://user-images.githubusercontent.com/638756/219936541-75f97329-77c1-41fb-bcd3-d9fba87a3280.png">

**Comment by fmzarrinkelk** [comment]
On a small device, your sliders are way too short, while the text field and the switches are disproportionally large.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/638756/219936799-76b809ba-9bd8-4044-b0c2-47099d85ad21.png">

**Comment by fmzarrinkelk** [comment]
You need to check that the values are in range (0 to 1)

<img width="187" alt="image" src="https://user-images.githubusercontent.com/638756/219937009-066bd8c4-d94e-42e2-b31f-3b40c0cc1330.png">

**Comment by fmzarrinkelk** [comment]
Setting the switch off should set the corresponding color to 0, as asked in the prompt. 

<img width="992" alt="image" src="https://user-images.githubusercontent.com/638756/219937224-129fb3d9-360e-4b04-bf34-c661c30dda2b.png">

**Comment by fmzarrinkelk** [comment]
Setting to switch off on older versions of the OS crashes the app. That's probably because your Graddle's minSDK doesn't prevent the app to be installed there.

<img width="123" alt="image" src="https://user-images.githubusercontent.com/638756/219937493-eb155ebf-448c-4d1d-8b1a-196a2ed74472.png">

<img width="291" alt="image" src="https://user-images.githubusercontent.com/638756/219937675-011ffabb-b617-47ed-8a71-00d93ed630b5.png">

**Comment by salonimodi** [comment]
Thanks for detailed feedback!! 

![image](https://user-images.githubusercontent.com/32274053/219972876-1fac4675-9ffe-4e67-8322-c07b1cd2735e.png)

Portrait Mode

![image](https://user-images.githubusercontent.com/32274053/219972896-5bfce1f5-2c77-448a-8e3f-74295d3c13f6.png)

Landscape Mode

I made changes for:

1. Range validation of editText from 0 to 1.
2.  Updated landscape and portrait mode UI (Please find attached screenshot for same)
3. Reset button click must reset values to 0. I previously handled used "isChecked()" button to true. It is working for me. But now I also added "isEnabled()" to true. Hope it will work for you.

Please let me know, if any other change required.
